services:
  nginx:
    image: sync-tex-nginx:prod
    build:
      context: .
      dockerfile: nginx/Dockerfile
      args:
        GIT_SHA: ${GIT_SHA:-unknown}
        BUILD_DATE: ${BUILD_DATE:-unknown}
    restart: unless-stopped
    volumes: !reset []

  postgres-users:
    restart: unless-stopped

  users-service:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped

  postgres-projects:
    restart: unless-stopped

  projects-service:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped

  collab-service:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped

  file-data-service:
    build:
      dockerfile: Dockerfile
    environment:
      RUST_LOG: info
    restart: unless-stopped

  postgres-assistant:
    restart: unless-stopped

  assistant-service:
    build:
      dockerfile: Dockerfile
    environment:
      LOG_LEVEL: info
    restart: unless-stopped

  minio:
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate --url http://nginx:80
    restart: unless-stopped
    depends_on:
      nginx:
        condition: service_started
    networks:
      - gateway-network
