// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: compaction.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CompactionService_CompactDocument_FullMethodName = "/compaction.CompactionService/CompactDocument"
	CompactionService_ExportDocument_FullMethodName  = "/compaction.CompactionService/ExportDocument"
)

// CompactionServiceClient is the client API for CompactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CompactionServiceClient interface {
	CompactDocument(ctx context.Context, in *CompactRequest, opts ...grpc.CallOption) (*CompactResponse, error)
	ExportDocument(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResponse, error)
}

type compactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCompactionServiceClient(cc grpc.ClientConnInterface) CompactionServiceClient {
	return &compactionServiceClient{cc}
}

func (c *compactionServiceClient) CompactDocument(ctx context.Context, in *CompactRequest, opts ...grpc.CallOption) (*CompactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompactResponse)
	err := c.cc.Invoke(ctx, CompactionService_CompactDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compactionServiceClient) ExportDocument(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportResponse)
	err := c.cc.Invoke(ctx, CompactionService_ExportDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompactionServiceServer is the server API for CompactionService service.
// All implementations must embed UnimplementedCompactionServiceServer
// for forward compatibility.
type CompactionServiceServer interface {
	CompactDocument(context.Context, *CompactRequest) (*CompactResponse, error)
	ExportDocument(context.Context, *ExportRequest) (*ExportResponse, error)
	mustEmbedUnimplementedCompactionServiceServer()
}

// UnimplementedCompactionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCompactionServiceServer struct{}

func (UnimplementedCompactionServiceServer) CompactDocument(context.Context, *CompactRequest) (*CompactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompactDocument not implemented")
}
func (UnimplementedCompactionServiceServer) ExportDocument(context.Context, *ExportRequest) (*ExportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportDocument not implemented")
}
func (UnimplementedCompactionServiceServer) mustEmbedUnimplementedCompactionServiceServer() {}
func (UnimplementedCompactionServiceServer) testEmbeddedByValue()                           {}

// UnsafeCompactionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompactionServiceServer will
// result in compilation errors.
type UnsafeCompactionServiceServer interface {
	mustEmbedUnimplementedCompactionServiceServer()
}

func RegisterCompactionServiceServer(s grpc.ServiceRegistrar, srv CompactionServiceServer) {
	// If the following call panics, it indicates UnimplementedCompactionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CompactionService_ServiceDesc, srv)
}

func _CompactionService_CompactDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompactionServiceServer).CompactDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompactionService_CompactDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompactionServiceServer).CompactDocument(ctx, req.(*CompactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompactionService_ExportDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompactionServiceServer).ExportDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompactionService_ExportDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompactionServiceServer).ExportDocument(ctx, req.(*ExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CompactionService_ServiceDesc is the grpc.ServiceDesc for CompactionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CompactionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "compaction.CompactionService",
	HandlerType: (*CompactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CompactDocument",
			Handler:    _CompactionService_CompactDocument_Handler,
		},
		{
			MethodName: "ExportDocument",
			Handler:    _CompactionService_ExportDocument_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "compaction.proto",
}
