// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: compaction.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompactRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DownloadUrl     string                 `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	UploadUrl       string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	BaseSnapshotUrl string                 `protobuf:"bytes,3,opt,name=base_snapshot_url,json=baseSnapshotUrl,proto3" json:"base_snapshot_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompactRequest) Reset() {
	*x = CompactRequest{}
	mi := &file_compaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactRequest) ProtoMessage() {}

func (x *CompactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactRequest.ProtoReflect.Descriptor instead.
func (*CompactRequest) Descriptor() ([]byte, []int) {
	return file_compaction_proto_rawDescGZIP(), []int{0}
}

func (x *CompactRequest) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *CompactRequest) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *CompactRequest) GetBaseSnapshotUrl() string {
	if x != nil {
		return x.BaseSnapshotUrl
	}
	return ""
}

type CompactResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage       string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	UpdatesMerged      uint32                 `protobuf:"varint,3,opt,name=updates_merged,json=updatesMerged,proto3" json:"updates_merged,omitempty"`
	CompactedSizeBytes uint64                 `protobuf:"varint,4,opt,name=compacted_size_bytes,json=compactedSizeBytes,proto3" json:"compacted_size_bytes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CompactResponse) Reset() {
	*x = CompactResponse{}
	mi := &file_compaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactResponse) ProtoMessage() {}

func (x *CompactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactResponse.ProtoReflect.Descriptor instead.
func (*CompactResponse) Descriptor() ([]byte, []int) {
	return file_compaction_proto_rawDescGZIP(), []int{1}
}

func (x *CompactResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompactResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CompactResponse) GetUpdatesMerged() uint32 {
	if x != nil {
		return x.UpdatesMerged
	}
	return 0
}

func (x *CompactResponse) GetCompactedSizeBytes() uint64 {
	if x != nil {
		return x.CompactedSizeBytes
	}
	return 0
}

type ExportRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SnapshotUrl       string                 `protobuf:"bytes,1,opt,name=snapshot_url,json=snapshotUrl,proto3" json:"snapshot_url,omitempty"`
	PendingUpdatesUrl string                 `protobuf:"bytes,2,opt,name=pending_updates_url,json=pendingUpdatesUrl,proto3" json:"pending_updates_url,omitempty"`
	UploadUrl         string                 `protobuf:"bytes,3,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_compaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_compaction_proto_rawDescGZIP(), []int{2}
}

func (x *ExportRequest) GetSnapshotUrl() string {
	if x != nil {
		return x.SnapshotUrl
	}
	return ""
}

func (x *ExportRequest) GetPendingUpdatesUrl() string {
	if x != nil {
		return x.PendingUpdatesUrl
	}
	return ""
}

func (x *ExportRequest) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

type ExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ExportedBytes uint64                 `protobuf:"varint,3,opt,name=exported_bytes,json=exportedBytes,proto3" json:"exported_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	mi := &file_compaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_compaction_proto_rawDescGZIP(), []int{3}
}

func (x *ExportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExportResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ExportResponse) GetExportedBytes() uint64 {
	if x != nil {
		return x.ExportedBytes
	}
	return 0
}

var File_compaction_proto protoreflect.FileDescriptor

const file_compaction_proto_rawDesc = "" +
	"\n" +
	"\x10compaction.proto\x12\n" +
	"compaction\"~\n" +
	"\x0eCompactRequest\x12!\n" +
	"\fdownload_url\x18\x01 \x01(\tR\vdownloadUrl\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\x12*\n" +
	"\x11base_snapshot_url\x18\x03 \x01(\tR\x0fbaseSnapshotUrl\"\xa9\x01\n" +
	"\x0fCompactResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0eupdates_merged\x18\x03 \x01(\rR\rupdatesMerged\x120\n" +
	"\x14compacted_size_bytes\x18\x04 \x01(\x04R\x12compactedSizeBytes\"\x81\x01\n" +
	"\rExportRequest\x12!\n" +
	"\fsnapshot_url\x18\x01 \x01(\tR\vsnapshotUrl\x12.\n" +
	"\x13pending_updates_url\x18\x02 \x01(\tR\x11pendingUpdatesUrl\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x03 \x01(\tR\tuploadUrl\"v\n" +
	"\x0eExportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0eexported_bytes\x18\x03 \x01(\x04R\rexportedBytes2\xa8\x01\n" +
	"\x11CompactionService\x12J\n" +
	"\x0fCompactDocument\x12\x1a.compaction.CompactRequest\x1a\x1b.compaction.CompactResponse\x12G\n" +
	"\x0eExportDocument\x12\x19.compaction.ExportRequest\x1a\x1a.compaction.ExportResponseB\x1eZ\x1cprojects-service/proto;protob\x06proto3"

var (
	file_compaction_proto_rawDescOnce sync.Once
	file_compaction_proto_rawDescData []byte
)

func file_compaction_proto_rawDescGZIP() []byte {
	file_compaction_proto_rawDescOnce.Do(func() {
		file_compaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_compaction_proto_rawDesc), len(file_compaction_proto_rawDesc)))
	})
	return file_compaction_proto_rawDescData
}

var file_compaction_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_compaction_proto_goTypes = []any{
	(*CompactRequest)(nil),  // 0: compaction.CompactRequest
	(*CompactResponse)(nil), // 1: compaction.CompactResponse
	(*ExportRequest)(nil),   // 2: compaction.ExportRequest
	(*ExportResponse)(nil),  // 3: compaction.ExportResponse
}
var file_compaction_proto_depIdxs = []int32{
	0, // 0: compaction.CompactionService.CompactDocument:input_type -> compaction.CompactRequest
	2, // 1: compaction.CompactionService.ExportDocument:input_type -> compaction.ExportRequest
	1, // 2: compaction.CompactionService.CompactDocument:output_type -> compaction.CompactResponse
	3, // 3: compaction.CompactionService.ExportDocument:output_type -> compaction.ExportResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_compaction_proto_init() }
func file_compaction_proto_init() {
	if File_compaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_compaction_proto_rawDesc), len(file_compaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_compaction_proto_goTypes,
		DependencyIndexes: file_compaction_proto_depIdxs,
		MessageInfos:      file_compaction_proto_msgTypes,
	}.Build()
	File_compaction_proto = out.File
	file_compaction_proto_goTypes = nil
	file_compaction_proto_depIdxs = nil
}
