// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collaborators.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCollaborator = `-- name: GetCollaborator :one
SELECT project_id, user_id, role, invited_by, invited_at FROM project_collaborators
WHERE project_id = $1 AND user_id = $2
`

func (q *Queries) GetCollaborator(ctx context.Context, projectID pgtype.UUID, userID string) (ProjectCollaborator, error) {
	row := q.db.QueryRow(ctx, getCollaborator, projectID, userID)
	var i ProjectCollaborator
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.InvitedAt,
	)
	return i, err
}
