// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDirectory = `-- name: CreateDirectory :one
INSERT INTO directories (id, project_id, parent_id, name)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, parent_id, name
`

func (q *Queries) CreateDirectory(ctx context.Context, iD pgtype.UUID, projectID pgtype.UUID, parentID pgtype.UUID, name string) (Directory, error) {
	row := q.db.QueryRow(ctx, createDirectory,
		iD,
		projectID,
		parentID,
		name,
	)
	var i Directory
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentID,
		&i.Name,
	)
	return i, err
}

const createFile = `-- name: CreateFile :one
INSERT INTO files (id, directory_id, project_id, filename, storage_key, file_type)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, directory_id, project_id, filename, storage_key, file_type
`

type CreateFileParams struct {
	ID          pgtype.UUID `json:"id"`
	DirectoryID pgtype.UUID `json:"directory_id"`
	ProjectID   pgtype.UUID `json:"project_id"`
	Filename    string      `json:"filename"`
	StorageKey  string      `json:"storage_key"`
	FileType    FileType    `json:"file_type"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.ID,
		arg.DirectoryID,
		arg.ProjectID,
		arg.Filename,
		arg.StorageKey,
		arg.FileType,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.DirectoryID,
		&i.ProjectID,
		&i.Filename,
		&i.StorageKey,
		&i.FileType,
	)
	return i, err
}

const deleteDirectory = `-- name: DeleteDirectory :exec
DELETE FROM directories
WHERE id = $1
`

func (q *Queries) DeleteDirectory(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDirectory, id)
	return err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files
WHERE id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFile, id)
	return err
}

const deleteProjectDirectories = `-- name: DeleteProjectDirectories :exec
DELETE FROM directories
WHERE project_id = $1
`

func (q *Queries) DeleteProjectDirectories(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectDirectories, projectID)
	return err
}

const deleteProjectFiles = `-- name: DeleteProjectFiles :exec
DELETE FROM files
WHERE project_id = $1
`

func (q *Queries) DeleteProjectFiles(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectFiles, projectID)
	return err
}

const getDirectory = `-- name: GetDirectory :one
SELECT id, project_id, parent_id, name FROM directories
WHERE id = $1
`

func (q *Queries) GetDirectory(ctx context.Context, id pgtype.UUID) (Directory, error) {
	row := q.db.QueryRow(ctx, getDirectory, id)
	var i Directory
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentID,
		&i.Name,
	)
	return i, err
}

const getFile = `-- name: GetFile :one
SELECT id, directory_id, project_id, filename, storage_key, file_type FROM files
WHERE id = $1
`

func (q *Queries) GetFile(ctx context.Context, id pgtype.UUID) (File, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.DirectoryID,
		&i.ProjectID,
		&i.Filename,
		&i.StorageKey,
		&i.FileType,
	)
	return i, err
}

const listDirectoriesByParent = `-- name: ListDirectoriesByParent :many
SELECT id, project_id, parent_id, name FROM directories
WHERE project_id = $1 AND parent_id = $2
ORDER BY name ASC
`

func (q *Queries) ListDirectoriesByParent(ctx context.Context, projectID pgtype.UUID, parentID pgtype.UUID) ([]Directory, error) {
	rows, err := q.db.Query(ctx, listDirectoriesByParent, projectID, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Directory{}
	for rows.Next() {
		var i Directory
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ParentID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectoriesByProject = `-- name: ListDirectoriesByProject :many
SELECT id, project_id, parent_id, name FROM directories
WHERE project_id = $1
ORDER BY name ASC
`

func (q *Queries) ListDirectoriesByProject(ctx context.Context, projectID pgtype.UUID) ([]Directory, error) {
	rows, err := q.db.Query(ctx, listDirectoriesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Directory{}
	for rows.Next() {
		var i Directory
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ParentID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByDirectory = `-- name: ListFilesByDirectory :many
SELECT id, directory_id, project_id, filename, storage_key, file_type FROM files
WHERE directory_id = $1
ORDER BY filename ASC
`

func (q *Queries) ListFilesByDirectory(ctx context.Context, directoryID pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesByDirectory, directoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.DirectoryID,
			&i.ProjectID,
			&i.Filename,
			&i.StorageKey,
			&i.FileType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByProject = `-- name: ListFilesByProject :many
SELECT id, directory_id, project_id, filename, storage_key, file_type FROM files
WHERE project_id = $1
ORDER BY filename ASC
`

func (q *Queries) ListFilesByProject(ctx context.Context, projectID pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.DirectoryID,
			&i.ProjectID,
			&i.Filename,
			&i.StorageKey,
			&i.FileType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDirectory = `-- name: UpdateDirectory :one
UPDATE directories
SET name = $2
WHERE id = $1
RETURNING id, project_id, parent_id, name
`

func (q *Queries) UpdateDirectory(ctx context.Context, iD pgtype.UUID, name string) (Directory, error) {
	row := q.db.QueryRow(ctx, updateDirectory, iD, name)
	var i Directory
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentID,
		&i.Name,
	)
	return i, err
}

const updateFile = `-- name: UpdateFile :one
UPDATE files
SET filename = $2
WHERE id = $1
RETURNING id, directory_id, project_id, filename, storage_key, file_type
`

func (q *Queries) UpdateFile(ctx context.Context, iD pgtype.UUID, filename string) (File, error) {
	row := q.db.QueryRow(ctx, updateFile, iD, filename)
	var i File
	err := row.Scan(
		&i.ID,
		&i.DirectoryID,
		&i.ProjectID,
		&i.Filename,
		&i.StorageKey,
		&i.FileType,
	)
	return i, err
}
