// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type FileType string

const (
	FileTypeImage FileType = "image"
	FileTypeTex   FileType = "tex"
	FileTypePdf   FileType = "pdf"
	FileTypeOther FileType = "other"
)

func (e *FileType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FileType(s)
	case string:
		*e = FileType(s)
	default:
		return fmt.Errorf("unsupported scan type for FileType: %T", src)
	}
	return nil
}

type NullFileType struct {
	FileType FileType `json:"file_type"`
	Valid    bool     `json:"valid"` // Valid is true if FileType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFileType) Scan(value interface{}) error {
	if value == nil {
		ns.FileType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FileType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFileType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FileType), nil
}

type Directory struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
	ParentID  pgtype.UUID `json:"parent_id"`
	Name      string      `json:"name"`
}

type File struct {
	ID          pgtype.UUID `json:"id"`
	DirectoryID pgtype.UUID `json:"directory_id"`
	ProjectID   pgtype.UUID `json:"project_id"`
	Filename    string      `json:"filename"`
	StorageKey  string      `json:"storage_key"`
	FileType    FileType    `json:"file_type"`
}

type Project struct {
	ID        pgtype.UUID      `json:"id"`
	OwnerID   string           `json:"owner_id"`
	Name      pgtype.Text      `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type ProjectCollaborator struct {
	ProjectID pgtype.UUID      `json:"project_id"`
	UserID    string           `json:"user_id"`
	Role      string           `json:"role"`
	InvitedBy pgtype.Text      `json:"invited_by"`
	InvitedAt pgtype.Timestamp `json:"invited_at"`
}
