// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, owner_id, name, created_at)
VALUES ($1, $2, $3, NOW())
RETURNING id, owner_id, name, created_at
`

func (q *Queries) CreateProject(ctx context.Context, iD pgtype.UUID, ownerID string, name pgtype.Text) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, iD, ownerID, name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, owner_id, name, created_at FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectStructureAsJSON = `-- name: GetProjectStructureAsJSON :one
WITH RECURSIVE dir_tree AS (
  SELECT 
    id,
    project_id,
    parent_id,
    name,
    1 as depth
  FROM directories
  WHERE project_id = $1 AND parent_id IS NULL
  
  UNION ALL
  
  SELECT 
    d.id,
    d.project_id,
    d.parent_id,
    d.name,
    dt.depth + 1
  FROM directories d
  INNER JOIN dir_tree dt ON d.parent_id = dt.id
)
SELECT jsonb_build_object(
  'project_id', $1,
  'directories', jsonb_agg(DISTINCT jsonb_build_object(
    'id', dt.id,
    'parent_id', dt.parent_id,
    'name', dt.name,
    'depth', dt.depth
  )),
  'files', jsonb_agg(DISTINCT jsonb_build_object(
    'id', f.id,
    'directory_id', f.directory_id,
    'filename', f.filename,
    'storage_key', f.storage_key,
    'file_type', f.file_type
  )) FILTER (WHERE f.id IS NOT NULL)
) as structure
FROM dir_tree dt
LEFT JOIN files f ON dt.id = f.directory_id
`

func (q *Queries) GetProjectStructureAsJSON(ctx context.Context, jsonbBuildObject interface{}) ([]byte, error) {
	row := q.db.QueryRow(ctx, getProjectStructureAsJSON, jsonbBuildObject)
	var structure []byte
	err := row.Scan(&structure)
	return structure, err
}

const getShowcaseProjectIDs = `-- name: GetShowcaseProjectIDs :many
SELECT project_id FROM showcase_projects
`

func (q *Queries) GetShowcaseProjectIDs(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getShowcaseProjectIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var project_id pgtype.UUID
		if err := rows.Scan(&project_id); err != nil {
			return nil, err
		}
		items = append(items, project_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByOwner = `-- name: ListProjectsByOwner :many
SELECT 
    p.id, p.owner_id, p.name, p.created_at,
    'owner' AS role
FROM projects p
WHERE p.owner_id = $1
ORDER BY p.created_at DESC
`

type ListProjectsByOwnerRow struct {
	ID        pgtype.UUID      `json:"id"`
	OwnerID   string           `json:"owner_id"`
	Name      pgtype.Text      `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Role      string           `json:"role"`
}

func (q *Queries) ListProjectsByOwner(ctx context.Context, ownerID string) ([]ListProjectsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listProjectsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsByOwnerRow{}
	for rows.Next() {
		var i ListProjectsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByUser = `-- name: ListProjectsByUser :many
SELECT DISTINCT
    p.id, p.owner_id, p.name, p.created_at,
    CASE
        WHEN p.owner_id = $1 THEN 'owner'
        ELSE pc.role
    END AS role
FROM projects p
LEFT JOIN project_collaborators pc ON p.id = pc.project_id AND pc.user_id = $1
WHERE p.owner_id = $1 OR pc.user_id = $1
ORDER BY p.created_at DESC
`

type ListProjectsByUserRow struct {
	ID        pgtype.UUID      `json:"id"`
	OwnerID   string           `json:"owner_id"`
	Name      pgtype.Text      `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Role      interface{}      `json:"role"`
}

func (q *Queries) ListProjectsByUser(ctx context.Context, ownerID string) ([]ListProjectsByUserRow, error) {
	rows, err := q.db.Query(ctx, listProjectsByUser, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsByUserRow{}
	for rows.Next() {
		var i ListProjectsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectName = `-- name: UpdateProjectName :one
UPDATE projects
SET name = $2
WHERE id = $1
RETURNING id, owner_id, name, created_at
`

func (q *Queries) UpdateProjectName(ctx context.Context, iD pgtype.UUID, name pgtype.Text) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectName, iD, name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
