// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateProject(ctx context.Context, iD pgtype.UUID, ownerID string, name pgtype.Text) (Project, error)
	DeleteProject(ctx context.Context, id pgtype.UUID) error
	GetCollaborator(ctx context.Context, projectID pgtype.UUID, userID string) (ProjectCollaborator, error)
	GetProject(ctx context.Context, id pgtype.UUID) (Project, error)
	GetProjectStructureAsJSON(ctx context.Context, jsonbBuildObject interface{}) ([]byte, error)
	ListProjectsByOwner(ctx context.Context, ownerID string) ([]Project, error)
	ListProjectsByUser(ctx context.Context, ownerID string) ([]Project, error)
	UpdateProjectName(ctx context.Context, iD pgtype.UUID, name pgtype.Text) (Project, error)
}

var _ Querier = (*Queries)(nil)
