"""Created LLM usage tables

Revision ID: 0275c2c7346c
Revises: 
Create Date: 2026-04-08 23:26:11.084800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0275c2c7346c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_usage_log_user_id'), 'llm_usage_log', ['user_id'], unique=False)
    op.create_table('user_llm_keys',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('encrypted_key', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'provider')
    )
    op.create_table('user_llm_settings',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('monthly_token_limit', sa.Integer(), nullable=True),
    sa.Column('tokens_used_this_month', sa.Integer(), nullable=False),
    sa.Column('token_reset_date', sa.Date(), server_default=sa.text("date_trunc('month', now()) + interval '1 month'"), nullable=False),
    sa.Column('preferred_model', sa.String(), nullable=True),
    sa.Column('max_tokens_per_call', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_llm_settings')
    op.drop_table('user_llm_keys')
    op.drop_index(op.f('ix_llm_usage_log_user_id'), table_name='llm_usage_log')
    op.drop_table('llm_usage_log')
    # ### end Alembic commands ###
