"""Added tables requried for RAG-based automatic project context

Revision ID: 993e2d76e758
Revises: ac0bc3274d9b
Create Date: 2026-05-01 05:42:21.189331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '993e2d76e758'
down_revision: Union[str, Sequence[str], None] = 'ac0bc3274d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Manually enable pgvector extension before any vector columns are created
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_index_state',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('rag_file_index',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['rag_index_state.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rag_file_index_project', 'rag_file_index', ['project_id'], unique=False)
    op.create_index('uq_rag_file_index_project_file', 'rag_file_index', ['project_id', 'file_id'], unique=True)
    op.create_table('rag_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('section_path', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('section_heading', sa.Text(), nullable=True),
    sa.Column('first_line', sa.Text(), nullable=True),
    sa.Column('last_line', sa.Text(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('embedding', Vector(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'file_id'], ['rag_file_index.project_id', 'rag_file_index.file_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rag_chunks_project_file', 'rag_chunks', ['project_id', 'file_id'], unique=False)
    op.create_table('rag_retrieved_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('chunk_id', sa.String(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['rag_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rag_retrieved_chunks_message', 'rag_retrieved_chunks', ['message_id'], unique=False)
    # ### end Alembic commands ###

    # Manually add HNSW index after the table is created
    op.execute("""
        CREATE INDEX idx_rag_chunks_embedding
        ON rag_chunks
        USING hnsw (embedding vector_cosine_ops)
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rag_retrieved_chunks_message', table_name='rag_retrieved_chunks')
    op.drop_table('rag_retrieved_chunks')
    op.drop_index('idx_rag_chunks_project_file', table_name='rag_chunks')
    op.drop_table('rag_chunks')
    op.drop_index('uq_rag_file_index_project_file', table_name='rag_file_index')
    op.drop_index('idx_rag_file_index_project', table_name='rag_file_index')
    op.drop_table('rag_file_index')
    op.drop_table('rag_index_state')
    # ### end Alembic commands ###

    # Manually drob HNSW index
    op.execute("DROP INDEX IF EXISTS idx_rag_chunks_embedding")
    
    # Manually drop vector extension
    op.execute("DROP EXTENSION IF EXISTS vector")
